### ISSUE TITLE
Implement KMeans.predict()

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#389] opened 2019-09-26 14:31 UTC
**Feature functionality**

Implement the method KMeans(k).predict(X) that, similar to the sklearn equivalent, will "Predict the closest cluster each sample in X belongs to."

https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html

**Comment by ClaudiaComito** [comment] 2019-09-26 14:56
@Cdebus there you go.

**Comment by Markus-Goetz** [comment] 2019-09-26 15:21
Isnt that a duplicate of #87 ?

**Closed** 2019-09-27 13:38 UTC
Labels: duplicate, enhancement, high-level functions
