### ISSUE TITLE
Duplicate MPI Communicator

### ISSUE THREAD

**Issue by mtar** [helmholtz-analytics/heat#895] opened 2021-12-08 13:51 UTC
**Description**
Duplicate MPI_COMM_WORLD for the default communicator.

**Comment by Dhruv454000** [comment] 2022-03-24 13:20
Hello @mtar , I would like to work on this one , I know about MPI_COMM_DUP , How can I start any guidance would be great.

**Comment by mtar** [comment] 2022-03-24 16:47
Hello @Dhruv454000, your help is much appreciated. Here are some details on this issue:

In communication.py, our default communicator is an instance of `MPICommunicaton` that uses MPI.COMM_WORLD as a handle
https://github.com/helmholtz-analytics/heat/blob/dd1b83d6d8b36cb4a70eefc631f00277b0745fee/heat/core/communication.py#L1886-L1890
To make our library more independent, however,  we need a duplicate of MPI_COMM_WORLD as the handle instead.

**Comment by Dhruv454000** [comment] 2022-03-25 06:06
#940 I have made a duplicate of MPI_COMM_WORLD @mtar

**Closed** 2022-03-30 13:58 UTC
Labels: MPI
