### ISSUE TITLE
parallel matrix multiplication for non-splitted heat tensors

### ISSUE THREAD

**Issue by krajsek** [helmholtz-analytics/heat#285] opened 2019-05-28 18:36 UTC
This issue investigates possible optimization strategies to #108

**Comment by Markus-Goetz** [comment] 2019-05-29 11:08
Duplicate of 108?

**Comment by krajsek** [comment] 2019-05-29 15:20
This issue investigates possible optimization strategies to #108

**Comment by coquelin77** [comment] 2019-06-03 14:27
Wouldn't this be taken care of by torch? I was under the impression that torch will parallelize this internally, is this not the case?

Are you suggesting that we should write our own algorithm for this?

**Closed** 2019-06-27 13:01 UTC
