### ISSUE TITLE
Offset and strides of slices/views are not correctly used in MPI

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#301] opened 2019-06-05 08:48 UTC
Consider the following example:

```
x = ht.ones((6,1), split=0) 
y = ht.ones((6,1))
print(ht.mul(x, y[1]))
```
Will result in an error, while 

```
print(ht.mu(x,y[1].copy()))
```
works fine. Working hypothesis of this bug is that the offsets and strides of the slice/view (a reference to the initial base buffer) are not correctly read out in the `ht.core.communication.as_buffer()` method.

**Comment by coquelin77** [comment] 2019-07-17 12:29
i am unable to reproduce this locally. can you add an error message?

**Comment by Cdebus** [comment] 2019-07-25 10:57
I can have a look at it when I'm reworking the binary operations

**Comment by ClaudiaComito** [comment] 2019-11-27 09:28
I can't reproduce it either, anyway, FWIW, torch.clone() doesn't preserve the memory format, see https://github.com/pytorch/pytorch/pull/30089 . The original memory-layout / stride information is lost in the current implementation of ht.copy().

**Comment by mtar** [comment] 2020-06-16 14:28
Bump
What's the status?

**Comment by coquelin77** [comment] 2020-06-16 14:34
im still unable to reproduce this. unless someone objects i will close it tomorrow

**Comment by coquelin77** [comment] 2020-06-16 14:34
perhaps this was fixed with the slicing

**Comment by lenablind** [comment] 2021-02-04 14:02
> im still unable to reproduce this. unless someone objects i will close it tomorrow

I guess this is a silent approval :D May you/someone close the issue? @coquelin77 @ClaudiaComito @Markus-Goetz

**Closed** 2021-02-04 14:04 UTC
Labels: bug :bug:
