### ISSUE TITLE
Add custom __str__ and __repr__ functions for tensors

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#89] opened 2018-11-28 17:42 UTC
Currently, we are using the print functions of pytorch to print tensors to standard out.

Implement a custom version that deals with distributed tensors

**Comment by ClaudiaComito** [comment] 2019-07-31 11:18
I'm giving up this Issue as I'd rather focus on the higher-level algorithms. @simon-schmitz would you like to take it on?

**Comment by simon-schmitz** [comment] 2019-07-31 13:02
I can take it on @ClaudiaComito. Is there already some code and/or more information on this issue?

**Comment by Markus-Goetz** [comment] 2020-04-03 10:37
Bump. What is the status on this?

**Comment by simon-schmitz** [comment] 2020-04-07 16:22
Unfortunately I won't get time to work on this anytime soon. So far I don't have decent code for this. If the issue is urgent I'd suggest to assign it to somebody else. Otherwise I could tackle this again at some point in the next month.

**Closed** 2020-07-01 13:23 UTC
Labels: good first issue
