### ISSUE TITLE
Provide fft()

### ISSUE THREAD

**Issue by Markus-Goetz** [helmholtz-analytics/heat#241] opened 2019-04-16 08:40 UTC

**Comment by mtar** [comment] 2020-03-17 15:28
These packages may be useful:
- [mpi4py-fft](https://mpi4py-fft.readthedocs.io/en/latest/)
- [FluidFFT](https://fluidfft.readthedocs.io/en/latest/index.html)

**Comment by dfsp-spirit** [comment] 2023-01-12 10:05
This would be very much appreciated indeed, as discussed with @ClaudiaComito.

**Comment by ClaudiaComito** [comment] 2023-02-08 13:01
closing this as duplicate of #1097

**Closed by ClaudiaComito** 2023-02-08 13:01 UTC
Labels: enhancement, help wanted, high-level functions, MPI
