### ISSUE TITLE
bugfix in Lasso demo

### ISSUE THREAD

**Issue by krajsek** [helmholtz-analytics/heat#539] opened 2020-04-09 08:53 UTC
**Description**
Removing Numpy and PyTorch examples in regression/lasso breaks the corresonding demo
and must be removed there too.

**To Reproduce**
run demo.py in examples/lasso

**Comment by Markus-Goetz** [comment] 2020-04-09 09:19
Duplicate of #529 .

**Closed by Markus-Goetz** 2020-04-09 09:19 UTC
Labels: bug :bug:
